[redis_nodes]
redis-node-1 ansible_host=localhost ansible_port=2221 container_ip=10.10.0.11
redis-node-2 ansible_host=localhost ansible_port=2222 container_ip=10.10.0.12
redis-node-3 ansible_host=localhost ansible_port=2223 container_ip=10.10.0.13
redis-node-4 ansible_host=localhost ansible_port=2224 container_ip=10.10.0.14
redis-node-5 ansible_host=localhost ansible_port=2225 container_ip=10.10.0.15
redis-node-6 ansible_host=localhost ansible_port=2226 container_ip=10.10.0.16

[redis_masters]
redis-node-1 ansible_host=localhost ansible_port=2221 container_ip=10.10.0.11
redis-node-2 ansible_host=localhost ansible_port=2222 container_ip=10.10.0.12
redis-node-3 ansible_host=localhost ansible_port=2223 container_ip=10.10.0.13

[redis_replicas]
redis-node-4 ansible_host=localhost ansible_port=2224 container_ip=10.10.0.14
redis-node-5 ansible_host=localhost ansible_port=2225 container_ip=10.10.0.15
redis-node-6 ansible_host=localhost ansible_port=2226 container_ip=10.10.0.16

[redis_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/redis_cluster_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
